"""Client for fabric-agent, the privileged host-side API (src/agent/): one file per agent route, all
importable from here (`from webui import agentclient as actions`)."""
from webui.agentclient.connection import configure, set_token  # noqa: F401
from webui.agentclient.constants import RECORD_TYPES  # noqa: F401
from webui.agentclient.errors import AgentError, AuthError, PermissionDenied, ValidationError  # noqa: F401
from webui.agentclient.add_client_class import add_client_class  # noqa: F401
from webui.agentclient.add_radius_client import add_radius_client  # noqa: F401
from webui.agentclient.add_record import add_record  # noqa: F401
from webui.agentclient.add_reservation import add_reservation  # noqa: F401
from webui.agentclient.add_subnet import add_subnet  # noqa: F401
from webui.agentclient.apply_changes import apply_changes  # noqa: F401
from webui.agentclient.audit import audit  # noqa: F401
from webui.agentclient.raise_signin_layer import raise_signin_layer  # noqa: F401
from webui.agentclient.security_layers import security_layers  # noqa: F401
from webui.agentclient.ca_summary import ca_summary  # noqa: F401
from webui.agentclient.convert_cert import convert_cert  # noqa: F401
from webui.agentclient.create_person import create_person  # noqa: F401
from webui.agentclient.create_tsig_key import create_tsig_key  # noqa: F401
from webui.agentclient.delete_device import delete_device  # noqa: F401
from webui.agentclient.delete_record import delete_record  # noqa: F401
from webui.agentclient.delete_role import delete_role  # noqa: F401
from webui.agentclient.delete_tsig_key import delete_tsig_key  # noqa: F401
from webui.agentclient.describe_csr import describe_csr  # noqa: F401
from webui.agentclient.device_overview import device_overview  # noqa: F401
from webui.agentclient.dhcp_overview import dhcp_overview  # noqa: F401
from webui.agentclient.dns_filter_change import dns_filter_change  # noqa: F401
from webui.agentclient.dns_filter_overview import dns_filter_overview  # noqa: F401
from webui.agentclient.host_changes import host_changes  # noqa: F401
from webui.agentclient.inspect_pem import inspect_pem  # noqa: F401
from webui.agentclient.issue_key_pair import issue_key_pair  # noqa: F401
from webui.agentclient.link_device_cert import link_device_cert  # noqa: F401
from webui.agentclient.list_issued import list_issued  # noqa: F401
from webui.agentclient.list_people import list_people  # noqa: F401
from webui.agentclient.list_tsig_keys import list_tsig_keys  # noqa: F401
from webui.agentclient.list_zones import list_zones  # noqa: F401
from webui.agentclient.query_log import query_log  # noqa: F401
from webui.agentclient.map_radius_group import map_radius_group  # noqa: F401
from webui.agentclient.radius_guides import radius_guides  # noqa: F401
from webui.agentclient.radius_overview import radius_overview  # noqa: F401
from webui.agentclient.read_audit import read_audit  # noqa: F401
from webui.agentclient.relaxed_settings import relaxed_settings  # noqa: F401
from webui.agentclient.cert_warnings import cert_warnings  # noqa: F401
from webui.agentclient.revoke_cert import revoke_cert  # noqa: F401
from webui.agentclient.remove_client_class import remove_client_class  # noqa: F401
from webui.agentclient.remove_radius_client import remove_radius_client  # noqa: F401
from webui.agentclient.remove_reservation import remove_reservation  # noqa: F401
from webui.agentclient.remove_subnet import remove_subnet  # noqa: F401
from webui.agentclient.reset_sign_in import reset_sign_in  # noqa: F401
from webui.agentclient.person_action import person_action  # noqa: F401
from webui.agentclient.reverse_zones import reverse_zones  # noqa: F401
from webui.agentclient.rotate_radius_secret import rotate_radius_secret  # noqa: F401
from webui.agentclient.rotate_tsig_key import rotate_tsig_key  # noqa: F401
from webui.agentclient.save_device import save_device  # noqa: F401
from webui.agentclient.save_role import save_role  # noqa: F401
from webui.agentclient.service_status import service_status  # noqa: F401
from webui.agentclient.set_option import set_option  # noqa: F401
from webui.agentclient.sign_csr import sign_csr  # noqa: F401
from webui.agentclient.unmap_radius_group import unmap_radius_group  # noqa: F401
from webui.agentclient.unset_option import unset_option  # noqa: F401
from webui.agentclient.update_subnet import update_subnet  # noqa: F401
from webui.agentclient.vault_add_kmip import vault_add_kmip  # noqa: F401
from webui.agentclient.vault_add_security_key import vault_add_security_key  # noqa: F401
from webui.agentclient.vault_add_usb import vault_add_usb  # noqa: F401
from webui.agentclient.vault_devices import vault_devices  # noqa: F401
from webui.agentclient.vault_rotate import vault_rotate  # noqa: F401
from webui.agentclient.vault_slot_action import vault_slot_action  # noqa: F401
from webui.agentclient.vault_slots import vault_slots  # noqa: F401
from webui.agentclient.vault_status import vault_status  # noqa: F401
from webui.agentclient.version_info import version_info  # noqa: F401
from webui.agentclient.zone_detail import zone_detail  # noqa: F401
from webui.agentclient.domain_overview import domain_overview  # noqa: F401
from webui.agentclient.gpo_overview import gpo_overview  # noqa: F401
from webui.agentclient.gpo_change import gpo_change  # noqa: F401
from webui.agentclient.add_machine import add_machine  # noqa: F401
from webui.agentclient.machine_action import machine_action  # noqa: F401
from webui.agentclient.federation_overview import federation_overview  # noqa: F401
from webui.agentclient.image_rows import image_rows  # noqa: F401
from webui.agentclient.start_job import start_job  # noqa: F401
from webui.agentclient.read_job import read_job  # noqa: F401
from webui.agentclient.acme_overview import acme_overview  # noqa: F401
