#!/usr/bin/env python3
"""Generate the function reference — manual chapter 1.11 — from the product's structured docstrings, with each
Python function's static callers (design: manual 1.11.1).

    python3 scripts/docs/gen_lib_doc.py           write the 1.11 subchapters, their numbers and the Volume 1 index
    python3 scripts/docs/gen_lib_doc.py --check   exit 1 if any of them is not what the code says

Never edit the generated subchapters by hand: edit the docstring, then regenerate.
"""
import datetime
import os
import re
import sys

from call_graph import call_graph
from lib_doc_registry import REGISTRY, number_items
from product_code import OPTIONAL, REPO, SECTIONS, functions

OUT = os.path.join(REPO, "docs", "volume_1_systems_and_services")
INDEX = os.path.join(OUT, "README.md")
BEGIN, END = "<!-- generated by scripts/docs/gen_lib_doc.py: 1.11 -->", "<!-- end of generated 1.11 -->"
NOTE = "Generated from the code's docstrings by `scripts/docs/gen_lib_doc.py` ([1.11.1](1.11.1-about-the-reference.md)): do not edit."
# what each page covers (the index shows it; a page not listed here shows its name only)
ABOUT = {
    "webui": "Open Fabric web UI: server, pages, fabric-agent client, OIDC, CA-pinned TLS, dev preview",
    "installers": "The Debian package wrapper",
    "fabricctl-lib": "Entry points: the deploy engine, the vars editor, the Keycloak configuration",
    "fabricctl-agent": "fabric-agent: the permission-checked host API behind the web UI",
    "fabricctl-jinja": "Code that runs inside service containers (389-DS seeding, FreeRADIUS policy)",
    "fabriclib-core": "fabriclib's command router (cli.py)",
    "fabriclib-common": "Shared helpers: paths, vars file, locking, audit, rendering, console output",
    "fabriclib-deploy": "The deploy engine: secrets, settings, render, install, restart",
    "fabriclib-dhcp": "Optional DHCP (Kea): settings, config, reservations, leases",
    "fabriclib-dns": "Zones, records, reverse zones, TSIG keys, ACLs, BIND reloads",
    "fabriclib-images": "Container images: status, update with rollback, prune",
    "fabriclib-keycloak": "Keycloak: people, roles, sign-in resets, token verification",
    "fabriclib-ldap": "389-DS: devices, device roles, people, the admin user",
    "fabriclib-logs": "Optional log forwarding (Fluent Bit)",
    "fabriclib-menu": "The vars editor (fabricctl --interactive), --print and --apply",
    "fabriclib-ntp": "Time: chrony on the host, its settings and checks",
    "fabriclib-pki": "Certificates: service certificates, manual issuing, CSR signing, conversion",
    "fabriclib-radius": "Optional 802.1X (FreeRADIUS): clients, groups, setup guides, decisions",
    "fabriclib-rbac": "Who may do what: permissions, bundles, route table",
    "fabriclib-secrets": "fabric's own secrets: file or OpenBao",
    "fabriclib-security": "Host firewall for Docker-published ports",
    "fabriclib-setup": "fabricctl setup / doctor / uninstall / restore: one step per file",
    "fabriclib-system": "Service status, start/stop, apply, version",
    "fabriclib-vault": "OpenBao: unlock methods (key slots), status, rotation, OIDC, break glass",
}


def page_for(path):
    """Purpose: which page of the reference a source file belongs on.
    Inputs:  path — a product file, repository-relative.
    Returns: page name (unchanged by the 2026-10 layout move, so the numbers stay, manual 1.11.1.2): webui
             (src/webui, src/ux/web), installers (packaging/, scripts/), fabricctl-agent (src/agent), fabricctl-jinja
             (src/containers: code that runs inside service containers), fabriclib-<domain>, fabricctl-lib (the
             CLI's entry points in src/ux/cli, and src/federation).
    Fails:   never.
    Feeds:   render_pages."""
    parts = path.split("/")
    if parts[:2] == ["src", "webui"] or parts[:3] == ["src", "ux", "web"]:
        return "webui"
    if parts[:2] in (["src", "containers"], ["packaging", "images"]):     # code that runs inside a container
        return "fabricctl-jinja"
    if parts[0] in ("packaging", "scripts"):
        return "installers"
    if parts[:2] == ["src", "agent"]:
        return "fabricctl-agent"
    if parts[:2] == ["src", "fabriclib"]:
        return "fabriclib-" + (parts[2] if len(parts) > 3 else "core")
    return "fabricctl-lib"


def _cell(text):
    return (text or "—").replace("|", "\\|").replace("\n", " ")


def _gone(removed):
    return f"This item has been removed from scope of fabric as of {removed}. See this chapter for what replaced it."


def render_pages(fns, callers, removed_on):
    """Purpose: the reference's subchapters, the registry text and the Volume 1 index block.
    Inputs:  fns — product_code.functions(); callers — call_graph(fns); removed_on — "<version> / <date>" for
             items found gone now.
    Returns: ({file name: Markdown}, registry text, index block lines).
    Fails:   OSError / ValueError from number_items (an unreadable registry).
    Feeds:   main (writes or compares them)."""
    pages, by_key = {}, {}
    for fn in sorted(fns, key=lambda f: (f["path"], f["line"])):
        files = pages.setdefault(page_for(fn["path"]), {})
        quals = files.setdefault(fn["path"], [])
        qual, n = fn["qualname"], 2
        while qual in quals:                                    # the same name twice in one file
            qual, n = f"{fn['qualname']} ({n})", n + 1
        quals.append(qual)
        by_key[(fn["path"], qual)] = fn
    rows, registry = number_items(pages, removed_on)

    def items(kind, prefix):
        out = []
        for (k, key), (num, removed) in rows.items():
            if k == kind and key.startswith(prefix) and "|" not in key[len(prefix):].split(" (gone ")[0]:
                out.append((num, key[len(prefix):].split(" (gone ")[0], removed))
        return sorted(out)

    out, index = {}, ["## 1.11 Function reference", "", "- [1.11.1 About the function reference](1.11.1-about-the-reference.md)"]
    for s, page, page_removed in items("page", ""):
        name = f"1.11.{s}-{page}.md"
        about = ABOUT.get(page, "")
        if page_removed:
            out[name] = f"# 1.11.{s} [DELETED] {page}\n\n{_gone(page_removed)}\n"
            index.append(f"- [1.11.{s} [DELETED] {page}]({name})")
            continue
        index.append(f"- [1.11.{s} {page}]({name})" + (f" — {about}" if about else ""))
        files = items("file", f"{page}|")
        lines = [f"# 1.11.{s} {page}", "", NOTE + (f" {about}." if about else ""), "", "Topics:"]
        lines += [f"- 1.11.{s}.{t} {'[DELETED] ' if r else ''}`{src}`" for t, src, r in files] + [""]
        for t, src, removed in files:
            if removed:
                lines += [f"## 1.11.{s}.{t} [DELETED] `{src}`", "", _gone(removed), ""]
                continue
            lines += [f"## 1.11.{s}.{t} `{src}`", ""]
            for u, qual, fremoved in items("function", f"{page}|{src}|"):
                if fremoved:
                    lines += [f"### 1.11.{s}.{t}.{u} [DELETED] `{qual}`", "", _gone(fremoved), ""]
                    continue
                fn = by_key[(src, qual)]
                lines += [f"### 1.11.{s}.{t}.{u} `{fn['qualname']}{fn['signature'] if fn['kind'] == 'py' else '()'}`",
                          "", "| | |", "|---|---|"]
                lines += [f"| {x} | {_cell(fn['sections'].get(x))} |" for x in SECTIONS]
                lines += [f"| {x} | {_cell(fn['sections'][x])} |" for x in OPTIONAL if fn["sections"].get(x)]
                if fn["kind"] == "py":
                    who = callers.get((fn["path"], fn["qualname"])) or []
                    lines.append(f"| Called by | {_cell(', '.join(f'`{c}`' for c in who) if who else '— (no static caller)')} |")
                lines.append("")
        out[name] = "\n".join(lines).rstrip() + "\n"
    return out, registry, index


def _with_index(text, block):
    """Purpose: the Volume 1 index with the generated 1.11 block replaced (or appended the first time)."""
    body = "\n".join([BEGIN] + block + [END])
    if BEGIN in text:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: body, text, flags=re.S)
    return text.rstrip("\n") + "\n\n" + body + "\n"


def main(argv):
    """Purpose: write the reference (1.11), its numbers and the Volume 1 index block, or check they are current.
    Inputs:  argv — ["--check"] to compare instead of writing.
    Returns: exit status: 0 written / current, 1 stale (the stale files listed).
    Fails:   OSError if a file cannot be read or written.
    Feeds:   tests/docs/run.py."""
    version = open(os.path.join(REPO, "config", "VERSION"), encoding="utf-8").read().strip()
    fns = functions()
    pages, registry, block = render_pages(fns, call_graph(fns), f"{version} / {datetime.date.today().isoformat()}")
    wanted = {os.path.join(OUT, n): t for n, t in pages.items()}
    wanted[REGISTRY] = registry
    wanted[INDEX] = _with_index(open(INDEX, encoding="utf-8").read(), block)
    if "--check" in argv:
        stale = [p for p, t in wanted.items()
                 if not os.path.exists(p) or open(p, encoding="utf-8").read() != t]
        for p in stale:
            print(f"stale: {os.path.relpath(p, REPO)}")
        print("the function reference is " + ("stale: run python3 scripts/docs/gen_lib_doc.py" if stale else "current"))
        return 1 if stale else 0
    for p, t in wanted.items():
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
    print(f"wrote the function reference (1.11): {len(pages)} pages, {len(fns)} functions")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
