#!/usr/bin/env python3
"""Generate docs/lib-doc/ — the function reference — from the product's
structured docstrings, with each Python function's static callers.

    python3 tests/docs/gen_lib_doc.py           write docs/lib-doc/
    python3 tests/docs/gen_lib_doc.py --check   exit 1 if docs/lib-doc/ is not what the code says

Never edit docs/lib-doc/ by hand: edit the docstring, then regenerate.
"""
import os
import sys

from call_graph import call_graph
from product_code import REPO, SECTIONS, functions

OUT = os.path.join(REPO, "docs", "lib-doc")
HEADER = "<!-- generated by tests/docs/gen_lib_doc.py from the code's docstrings: do not edit -->\n"


def page_for(path):
    """Purpose: which lib-doc page a source file belongs on.
    Inputs:  path — a product file, repository-relative.
    Returns: page name without .md: webui, installers, fabricctl-lib (the
             top-level lib files), fabricctl-agent, fabricctl-jinja (code
             that runs inside service containers), fabriclib-<domain>.
    Fails:   never.
    Feeds:   render_pages."""
    parts = path.split("/")
    if parts[0] in ("webui", "installers"):
        return parts[0]
    if parts[:2] == ["fabricctl", "jinja"]:
        return "fabricctl-jinja"
    if parts[:3] == ["fabricctl", "lib", "agent"]:
        return "fabricctl-agent"
    if parts[:3] == ["fabricctl", "lib", "fabriclib"]:
        return "fabriclib-" + (parts[3] if len(parts) > 4 else "core")
    return "fabricctl-lib"


def _cell(text):
    return (text or "—").replace("|", "\\|").replace("\n", " ")


def render_pages(fns, callers):
    """Purpose: the Markdown of every lib-doc page.
    Inputs:  fns — product_code.functions(); callers — call_graph(fns).
    Returns: {file name: Markdown} including README.md (the index).
    Fails:   never.
    Feeds:   main (writes or compares them)."""
    pages = {}
    for fn in sorted(fns, key=lambda f: (f["path"], f["line"])):
        pages.setdefault(page_for(fn["path"]), []).append(fn)
    out = {}
    index = [HEADER, "# Function reference\n",
             "Every function of `fabricctl/`, `webui/` and `installers/`: its purpose, inputs, result, how it "
             "fails and what uses the result. **Called by** is computed from the code (static calls only); "
             "**Feeds** is written by hand and also covers dynamic calls. Regenerate with "
             "`python3 tests/docs/gen_lib_doc.py` after changing a docstring.\n",
             "| Page | Functions | Files |", "|---|---|---|"]
    for page, items in sorted(pages.items()):
        files = sorted({f["path"] for f in items})
        index.append(f"| [{page}]({page}.md) | {len(items)} | {len(files)} |")
        lines = [HEADER, f"# {page}\n"]
        for path in files:
            lines.append(f"## `{path}`\n")
            for fn in (f for f in items if f["path"] == path):
                lines.append(f"### `{fn['qualname']}{fn['signature'] if fn['kind'] == 'py' else '()'}`\n")
                lines.append("| | |\n|---|---|")
                for s in SECTIONS:
                    lines.append(f"| {s} | {_cell(fn['sections'].get(s))} |")
                if fn["kind"] == "py":
                    who = callers.get((fn["path"], fn["qualname"])) or []
                    lines.append(f"| Called by | {_cell(', '.join(f'`{c}`' for c in who) if who else '— (no static caller)')} |")
                lines.append("")
        out[f"{page}.md"] = "\n".join(lines).rstrip() + "\n"
    out["README.md"] = "\n".join(index) + "\n"
    return out


def main(argv):
    """Purpose: write docs/lib-doc/, or check that it is current.
    Inputs:  argv — ["--check"] to compare instead of writing.
    Returns: exit status: 0 written / current, 1 stale (with the stale pages listed).
    Fails:   OSError if docs/lib-doc/ cannot be written.
    Feeds:   tests/docs/run.py."""
    fns = functions()
    pages = render_pages(fns, call_graph(fns))
    existing = {n for n in os.listdir(OUT)} if os.path.isdir(OUT) else set()
    if "--check" in argv:
        stale = [n for n, text in pages.items()
                 if not os.path.exists(os.path.join(OUT, n)) or open(os.path.join(OUT, n), encoding="utf-8").read() != text]
        stale += sorted(existing - set(pages))
        for n in stale:
            print(f"stale: docs/lib-doc/{n}")
        print("docs/lib-doc/ is " + ("stale: run python3 tests/docs/gen_lib_doc.py" if stale else "current"))
        return 1 if stale else 0
    os.makedirs(OUT, exist_ok=True)
    for n in existing - set(pages):
        os.remove(os.path.join(OUT, n))
    for n, text in pages.items():
        with open(os.path.join(OUT, n), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    print(f"wrote docs/lib-doc/: {len(pages)} pages, {len(fns)} functions")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
